import type { RegistryItem } from "@/lib/types";

const baseItem = {
  is_active: true,
  claimed_quantity: 0,
  remaining_quantity: 0,
  funded_usd: 0,
  funded_vnd: 0,
  remaining_usd: 0,
  remaining_vnd: 0,
};

const fixed: RegistryItem[] = [
  {
    ...baseItem,
    id: "11111111-1111-4111-8111-111111111111",
    title: "Pigeon glass bottles",
    description: "A practical set of glass feeding bottles for the everyday rotation.",
    image_path: "/products/pigeon-glass-bottle.png",
    category: "Feeding",
    item_type: "fixed",
    price_usd: 40,
    price_vnd: 1040000,
    quantity_needed: 2,
    fund_target_usd: null,
    fund_target_vnd: null,
    sort_order: 1,
    remaining_quantity: 2,
  },
  {
    ...baseItem,
    id: "44444444-4444-4444-8444-444444444444",
    title: "Baby bathtub",
    description: "A roomy PP baby tub with a removable support seat, non-slip handholds, and an easy-drain plug for simpler newborn bath time.",
    image_path: "/products/baby-bathtub.jpg",
    category: "Bath",
    item_type: "fixed",
    price_usd: 15,
    price_vnd: 400000,
    quantity_needed: 1,
    fund_target_usd: null,
    fund_target_vnd: null,
    sort_order: 4,
    remaining_quantity: 1,
  },
  {
    ...baseItem,
    id: "55555555-5555-4555-8555-555555555555",
    title: "Diaper caddy",
    description: "A portable organizer with divided compartments and outer pockets for diapers, wipes, creams, and other changing essentials.",
    image_path: "/products/diaper-caddy.jpg",
    category: "Everyday",
    item_type: "fixed",
    price_usd: 7,
    price_vnd: 190000,
    quantity_needed: 1,
    fund_target_usd: null,
    fund_target_vnd: null,
    sort_order: 5,
    remaining_quantity: 1,
  },
];

const funds: RegistryItem[] = [
  {
    ...baseItem,
    id: "22222222-2222-4222-8222-222222222222",
    title: "BabyBjörn Bouncer Bliss fund",
    description: "An ergonomic mesh bouncer with natural baby-powered rocking, three recline positions, and a lightweight frame that folds flat for moving or storage.",
    image_path: "/products/babybjorn-bouncer-bliss.jpg",
    category: "Nursery",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 212,
    fund_target_vnd: 5500000,
    sort_order: 2,
    remaining_usd: 212,
    remaining_vnd: 5500000,
  },
  {
    ...baseItem,
    id: "33333333-3333-4333-8333-333333333333",
    title: "Foldable changing table fund",
    description: "A practical height-adjustable changing station with a wipe-clean top, side organizer, lower shelf, and lockable wheels.",
    image_path: "/products/foldable-changing-table.jpg",
    category: "Nursery",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 37,
    fund_target_vnd: 950000,
    sort_order: 3,
    remaining_usd: 37,
    remaining_vnd: 950000,
  },
  {
    ...baseItem,
    id: "66666666-6666-4666-8666-666666666666",
    title: "Crib mattress fund",
    description: "A firm, flat crib mattress for a wooden cot, with a lightly quilted surface and simple neutral finish.",
    image_path: "/products/crib-mattress.jpg",
    category: "Sleep",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 19,
    fund_target_vnd: 500000,
    sort_order: 6,
    remaining_usd: 19,
    remaining_vnd: 500000,
  },
  {
    ...baseItem,
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    title: "Ergobaby Omni baby carrier fund",
    description: "A breathable, ergonomic carrier for hands-free walks, errands, and newborn-to-toddler snuggles.",
    image_path: "/products/ergobaby-omni-carrier.png",
    category: "On the go",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 200,
    fund_target_vnd: 5200000,
    sort_order: 7,
    remaining_usd: 200,
    remaining_vnd: 5200000,
  },
  {
    ...baseItem,
    id: "77777777-7777-4777-8777-777777777777",
    title: "Chilux V1.6 stroller fund",
    description: "A multifunction stroller with bassinet-style recline, adjustable handle, and sturdy wheels for everyday outings.",
    image_path: "/products/chilux-v16-stroller.png",
    category: "On the go",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 120,
    fund_target_vnd: 3120000,
    sort_order: 8,
    remaining_usd: 120,
    remaining_vnd: 3120000,
  },
  {
    ...baseItem,
    id: "88888888-8888-4888-8888-888888888888",
    title: "Chilux Peace wooden crib fund",
    description: "A sturdy 6-mode wooden crib/cot that can grow with Eva Vy from sleepy newborn days into toddler routines.",
    image_path: "/products/chilux-peace-crib.png",
    category: "Sleep",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 280,
    fund_target_vnd: 7280000,
    sort_order: 9,
    remaining_usd: 280,
    remaining_vnd: 7280000,
  },
  {
    ...baseItem,
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    title: "Baby Brezza Bottle Washer Pro fund",
    description: "An all-in-one countertop machine that washes up to four bottles and pump parts, then steam-sterilizes and hot-air dries them in one cycle.",
    image_path: "/products/baby-brezza-bottle-washer.jpg",
    category: "Feeding",
    item_type: "fund",
    price_usd: null,
    price_vnd: null,
    quantity_needed: null,
    fund_target_usd: 269,
    fund_target_vnd: 6990000,
    sort_order: 10,
    remaining_usd: 269,
    remaining_vnd: 6990000,
  },
];

export const demoItems = [...fixed, ...funds].sort(
  (a, b) => a.sort_order - b.sort_order,
);
